### PR TITLE
Avoid slow RubyGems update and re-enable TruffleRuby

### PR DESCRIPTION
**Pull request by eregon**
From the discussion on https://twitter.com/eregontp/status/1141272669297532928

### CODE REVIEW

**Comment by solnic** [comment]
Thank you!

**Comment by eregon** [comment]
Thanks for merging!
Don't hesitate to reach out if it becomes annoying again.
I'll try to spread the word that `gem update --system` is not needed in TravisCI, after checking with the Bundler team if that's correct for all cases (e.g., Ruby < 2.3).

**Comment by solnic** [comment]
> I'll try to spread the word that gem update --system is not needed in TravisCI

the reason why it was there is that at some point in the past something broke, quite possibly under JRuby, and the solution was to upgrade rubygems 🤷‍♂️

**Comment by eregon** [comment]
It was needed for Bundler 2.0.0, but fixed with 2.0.1, I think that's the reason many repos have it now.

**Pull request merged**
