### PR TITLE
Add colorize library as extension for SQL logger

### PR DESCRIPTION
**Pull request by davydovanton**
Reference to https://github.com/dry-rb/dry-monitor/issues/9

We change loading process for SQL logger colorize logic. Now we use dry-core extensions for load default (without anything) or rouge extension and disable or enable it when you need.

This patch will change a way how to setup color loggers. Now you need to load extension:
```ruby
Dry::Monitor::SQL::Logger.load_extensions(:rouge_colorizer)
```

Instead `colorize` option.

Also, it will allow to use custom extensions if you need it

### CODE REVIEW

**Comment by nijikon** [comment]
@solnic can you check if this is a good approach?

**Comment by solnic** [comment]
@nijikon yeah I'll get to it later this week

**Comment by davydovanton** [comment]
@solnic thanks, man! ❤️❤️❤️

**Comment by davydovanton** [comment]
@solnic we 🍐 with @mensfeld and update this PR. now we use dry-core extensions  for load colorizer instead exception flow.

Could you check it? I'll merge it and update documentations if you don't have any issues.

**Comment by davydovanton** [comment]
@solnic thanks!

**Comment by mensfeld** [comment]
@solnic will you craft a release? I would love to get rid of this:
zrzut ekranu z 2019-01-21 17-21-04

**Pull request merged**
